### ISSUE TITLE
Option for "sticky" class add/removed when actually "stuck"

### ISSUE THREAD

**Issue by famgam** [alextaujenis/jquery-stuck#3]
Currently my CSS has to include something like div[class*="position: fixed"], a nice addition would be to have a class dynamically added and removed when the "stuck" element is in it's static state versus stuck respectively.

eg:  

<div class="stuck">Some content to stick</div>

eg: [scroll lower on the page]

<div class="stuck is_stuck">Some content to stick</div>

eg:  [scroll back to top of page]

<div class="stuck">Some content to stick</div>

This class name should have a default ("is_stuck" or something, who really cares what as long as it makes sense) and allow to be overridden in the options parameter. As I find it commonly fighting against other design elements on the page after scrolling. Especially already fixed elements (the new stuck elements end up behind them instead of under them) Having a "is_stuck" class would allow style modications to an element after it's been positioned as fixed. (ie, like add margin, borders, dropshadows, etc...)

I could write up an example bit of code that would achieve this to submit, just let me know if this would be useful.

**Comment by alextaujenis** [comment]
I think the main issue here is the plugin messes with the z-index. It clears it when released then pushes it to 99 when stuck, which worked well for a static site with a default install of foundation.

Your solution of adding something like an .is-stuck class to the div would give z-index control back into the hands of the designer.

As for your comment about position:fixed elements: You should be able to give them a .stuck class and the other elements will stack underneath. Let me know if your page behaves differently.

**Comment by jgclifton** [comment]
Not saying this is a perfect solution, but something like the following works for adding this feature:

```
            $( window ).scroll(function() {
                $( ".stuck" ).each(function() {
                    if ($(this).css('position') === 'fixed'){
                       $(this).addClass('is_stuck');
                    } else if ($(this).css('position') === 'relative'){
                        $(this).removeClass('is_stuck');
                    }
                });
            });
```

There are reasons why it's not the worst idea to give the designer control over z-index. I've used it where there's a dropdown menu on mobile, with another stuck element underneath. The desired effect was that if the menu was open, then the menu would go over the top of the next stuck element. As they had the same z-index this was not reliable; it's easily overcome with an ID however and !important.

**Comment by famgam** [comment]
Hey I appreciate the responses and the time. But I gave up on this plugin. Firefox implements this feature natively, and it works perfectly. When Edge, Chrome and Safari catch up, it will just work there as well. I am too tired of hacking features into apps and sites these days. Especially when all it takes is to be patient and the browsers will fix this in the near future.

Again, thanks for your time and effort.
